# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetails',
        ),
    ]
