# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_delete_eventdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='performer',
        ),
        migrations.AddField(
            model_name='performer',
            name='eventName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventsapp.Event'),
        ),
    ]
