# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0003_auto_20170527_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='eventName',
            new_name='event',
        ),
    ]
